name: Deploy Production

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: 22

          script: |
            set -e

            echo "Pulling latest code..."
            cd /splitapp 

            git pull origin ${{ github.ref_name }}

            echo "Rebuilding containers..."
            docker compose up -d --build

            echo "Deployment finished"